### ISSUE TITLE
Please update the theme for gtk-3.18+

### ISSUE THREAD

**Issue by AnwarShah** [spagy/Flattastic#1]
This theme was a good theme, but it hasn't been updated recently. Please update the theme to work with gtk-3.18 and later. gtk-3.18 is used by Ubuntu 16.04 LTS

**Comment by spagy** [comment]
this repo is just a github mirror of [the original deviant art project](https://nale12.deviantart.com/art/Flattastic-11-03-2014-424913255). hosting on github makes the theme much easier to package for the aur.

unfortunately, it looks like the original author hasn't updated the theme since early 2014. you could have a look at the [arc theme](https://github.com/horst3180/Arc-theme) as an alternative. it's a more modern, flat gtk theme.

**Comment by AnwarShah** [comment]
@spagy Thanks for the reply. I did installed arc theme, but I thought it's quite different and would be glad if it was re-worked.
